Cars_ASPCore2/Models/IndividualButtonPartial.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Cars_ASPCore2.Models
{
    public class IndividualButtonPartial
    {
        public string ButtonType { get; set; }
        public string Action { get; set; }
        public string Text { get; set; }
        public string Glyph { get; set; }

        public int? ServiceId { get; set; }
        public string CustomerId { get; set; }
        public int? CarId { get; set; }
        public string ActionParameters {
            get
            {
                var param = new StringBuilder(@"/");
                if(ServiceId != null)
                {
                    if (ServiceId != 0)
                    {
                        param.Append(String.Format("{0}", ServiceId));
                    }
                }
               
                if(CustomerId != null)
                {
                    if (CustomerId.Length > 0) 
                    {
                        param.Append(String.Format("{0}", CustomerId));
                    }
                }
                if (CarId != null)
                {
                    if (CarId != 0)
                    {
                        param.Append(String.Format("{0}", CarId));
                    }
                }
                return param.ToString().Substring(0, param.Length);
            }

        }
    }
}

Cars_ASPCore2/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Cars_ASPCore2.Data;
using System.Security.Claims;
using Cars_ASPCore2.ViewModel;
using Cars_ASPCore2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Cars_ASPCore2.Controllers
{
    [Authorize]
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CarsController(ApplicationDbContext dbContext)
        {
            _db = dbContext;
        }
        public IActionResult Index(string userId = null)
        {
            if(userId == null)
            {
                //only called when a guest customer logs in
                userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            }

            var model = new CarAndCustomerViewModel
            {
                Cars = _db.Cars.Where(c => c.UserId == userId),
                UserObj = _db.Users.FirstOrDefault(u => u.Id == userId)
            };
            return View(model);
        }

        //Create GET
        public IActionResult Create(string userId)
        {
            Car carObj = new Car
            {
                Year = DateTime.Now.Year,
                UserId = userId,
            };
            return View(carObj);
        }

        //Create POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car car)
        {
            if (ModelState.IsValid)
            {
                _db.Add(car);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new Car {UserId = car.UserId});
            }

            return View(car);
        }
        //Details GET
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var car = await _db.Cars.Include(c => c.ApplicationUser).
                SingleOrDefaultAsync(m => m.Id == id);

            if (car == null)
            {
                return NotFound();
            }
            return View(car);
         
        }
        //Edit GET
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var car = await _db.Cars.Include(c => c.ApplicationUser).
                SingleOrDefaultAsync(m => m.Id == id);

            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }
        //Delete GET
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var car = await _db.Cars.Include(c => c.ApplicationUser).
                SingleOrDefaultAsync(m => m.Id == id);

            if (car == null)
            {
                return NotFound();
            }
            return View(car);

        }

        //EDit POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Car car)
        {
            if(id != car.Id)
            {
                
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Update(car);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { userId = car.UserId});
            }
            return View(car);
        }

        //Delete POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _db.Cars.SingleOrDefaultAsync(c => c.Id == id);
            if(car == null)
            {
                return NotFound();
            }
            var services = _db.Services.Where(c=>c.CarId == car.Id);
            _db.RemoveRange(services);
            _db.Cars.Remove(car);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new {userId = car.UserId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
    }
}

Cars_ASPCore2/Controllers/ServiceTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Cars_ASPCore2.Data;
using Cars_ASPCore2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Cars_ASPCore2.Utility;
namespace Cars_ASPCore2.Controllers
{
    [Authorize(Roles = StaticDetails.AdminEndUser)]
    public class ServiceTypesController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ServiceTypesController(ApplicationDbContext db)
        {
            _db = db;
        }
        //GET: ServiceType
        public IActionResult Index()
        {
            return View(_db.ServiceTypes.ToList());
        }
        //GET: ServiceType/Create
        public IActionResult Create()
        {
            return View();
        }
        //GET: ServiceType/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            var serviceType = await _db.ServiceTypes.SingleOrDefaultAsync(m => m.Id == id);
            if (serviceType == null)
            {
                return NotFound();
            }

            return View(serviceType);
        }
        //GET: ServiceType/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var serviceType = await _db.ServiceTypes.FirstOrDefaultAsync(m=>m.Id == id);
            if (serviceType == null) return NotFound();
            return View(serviceType);
        }
        //GET: ServiceType/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var serviceType = await _db.ServiceTypes.FirstOrDefaultAsync(m => m.Id == id);
            if (serviceType == null) return NotFound();
            return View(serviceType);
        }

        //POST-------------------------------------------------------------------------------

        //POST: ServiceType/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            ServiceType serviceTypes = await _db.ServiceTypes.FirstOrDefaultAsync(m => m.Id == id);
            _db.ServiceTypes.Remove(serviceTypes);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        //POST: ServiceType/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ServiceType serviceType)
        {
            if (id != serviceType.Id) return NotFound();
            if (ModelState.IsValid)
            {
                _db.ServiceTypes.Update(serviceType);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(serviceType);
        }
        //POST: ServiceType/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ServiceType serviceType)
        {
            if (ModelState.IsValid)
            {
               
                _db.ServiceTypes.Add(serviceType);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(serviceType);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
    }
}

Cars_ASPCore2/Views/Shared/_CarDetailsInServicePartial.cshtml
@model Cars_ASPCore2.ViewModel.CarInServicesViewModel
<h4>Car record for customer</h4>
<div class="row form-border">
    @* make and model *@
    <div class="col-sm-5">
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Make" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom:5px;">
                <input asp-for="Make" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Model" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom:5px;">
                <input asp-for="Model" disabled class="form-control" />
            </div>
        </div>
        
    </div>

    @* style and year *@
    <div class="col-sm-5 col-sm-offset-2">
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Style" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom:5px;">
                <input asp-for="Style" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Year" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom:5px;">
                <input asp-for="Year" disabled class="form-control" />
            </div>
        </div>
    </div>
</div>

Cars_ASPCore2/Views/Shared/_DisplayPastServices.cshtml
@model Cars_ASPCore2.ViewModel.CarInServicesViewModel
@using Cars_ASPCore2.Utility
<div>
    <table class="table table-condensed table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.PastServiceObject.FirstOrDefault().Miles)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.PastServiceObject.FirstOrDefault().Price)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.PastServiceObject.FirstOrDefault().Details)
            </th>

            <th>
                @Html.DisplayNameFor(m => m.PastServiceObject.FirstOrDefault().ServiceType.Name)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.PastServiceObject.FirstOrDefault().DateAdded)
            </th>
        </tr>
        @foreach(var item in Model.PastServiceObject)
        {
        <tr>
            <td>@Html.DisplayFor(m => item.Miles)</td>
            <td>@Html.DisplayFor(m => item.Price)</td>
            <td>@Html.DisplayFor(m => item.Details)</td>
            <td>@Html.DisplayFor(m => item.ServiceType.Name)</td>
            <td>@Html.DisplayFor(m => item.DateAdded)</td>
            <td>
                @if(item.DateAdded.Date == DateTime.Now.Date && User.IsInRole(StaticDetails.AdminEndUser))
                {
                    @Html.Partial("_IndividualButtonPartial",
                                    new IndividualButtonPartial { 
                                        Action="Delete",
                                        ButtonType="btn-danger",
                                        Glyph="trash",
                                        Text="Delete",
                                        ServiceId = item.Id
                                    })

                }
            </td>

        </tr>

        }
    </table>
</div>

Cars_ASPCore2/Views/Shared/_IndividualButtonPartial.cshtml
@model Cars_ASPCore2.Models.IndividualButtonPartial
<a type="button" class="btn btn-sm @Model.ButtonType" href="@Url.Action(Model.Action)@Model.ActionParameters">
        <span class="glyphicon glyphicon-@Model.Glyph">

        </span>
        <span class="sr-only">@Model.Text</span>
</a>

Cars_ASPCore2/Views/Shared/_Layout.cshtml
@using Cars_ASPCore2.Utility
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cars_ASPCore2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Cars_ASPCore2</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole(StaticDetails.AdminEndUser))
                    {
                        <li><a asp-area="" asp-controller="ServiceTypes" asp-action="Index">ServiceTypes</a></li>
                    }
                    @if (User.IsInRole(StaticDetails.AdminEndUser))
                    {
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                    }
                    <li><a asp-area="" asp-controller="Cars" asp-action="Index">Cars</a></li>

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>
    <footer class="footer">
        <div class="container">
            <p class="text-muted">&copy; 2018 - Cars_ASPCore2</p>
        </div>
      
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Cars_ASPCore2/Views/Shared/_TableButtonPartial.cshtml
@model Cars_ASPCore2.Models.IndividualButtonPartial

<td style="width:150px">
    <div class="btn-group" role="group">
        @Html.Partial("_IndividualButtonPartial",
     new IndividualButtonPartial {
         Action = "Edit",
         ButtonType = "btn-primary",
         Glyph = "pencil",
         Text = "Edit",
         ServiceId = Model.ServiceId,
         CustomerId = Model.CustomerId,
         CarId = Model.CarId
        })

        @Html.Partial("_IndividualButtonPartial",
    new IndividualButtonPartial {
        Action = "Delete",
        ButtonType = "btn-danger",
        Glyph = "trash",
        Text = "Delete",
        ServiceId = Model.ServiceId,
        CustomerId = Model.CustomerId,
        CarId = Model.CarId
    })

        @Html.Partial("_IndividualButtonPartial",
    new IndividualButtonPartial {
        Action = "Details",
        ButtonType = "btn-success",
        Glyph = "list",
        Text = "Details",
        ServiceId = Model.ServiceId,
        CustomerId = Model.CustomerId,
        CarId = Model.CarId
    })
        
    </div>
</td>