Cars_ASPCore2/Models/Service.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Cars_ASPCore2.Models;

namespace Cars_ASPCore2.Models
{
    public class Service
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public double Miles { get; set; }
        [Required]
        public double Price { get; set; }
        public string Details { get; set; }

        [Required]
        [DisplayFormat(DataFormatString ="{0:d}")]
        public DateTime DateAdded { get; set; }

        public int CarId { get; set; }
        public int ServiceTypeId { get; set; }
        [ForeignKey("CarId")]
        public virtual Car Car { get; set; }
        [ForeignKey("ServiceTypeId")]
        public virtual ServiceType ServiceType { get; set; }
    }
}

Cars_ASPCore2/Models/ServiceType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace Cars_ASPCore2.Models
{
    public class ServiceType
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
    }
}

Cars_ASPCore2/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Cars_ASPCore2.Data;
using System.Security.Claims;
using Cars_ASPCore2.ViewModel;
using Cars_ASPCore2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Cars_ASPCore2.Controllers
{
    [Authorize]
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CarsController(ApplicationDbContext dbContext)
        {
            _db = dbContext;
        }
        public IActionResult Index(string userId = null)
        {
            if(userId == null)
            {
                //only called when a guest customer logs in
                userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            }

            var model = new CarAndCustomerViewModel
            {
                Cars = _db.Cars.Where(c => c.UserId == userId),
                UserObj = _db.Users.FirstOrDefault(u => u.Id == userId)
            };
            return View(model);
        }

        //Create GET
        public IActionResult Create(string userId)
        {
            Car carObj = new Car
            {
                Year = DateTime.Now.Year,
                UserId = userId,
            };
            return View(carObj);
        }

        //Create POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car car)
        {
            if (ModelState.IsValid)
            {
                _db.Add(car);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new Car {UserId = car.UserId});
            }

            return View(car);
        }
        //Details GET
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var car = await _db.Cars.Include(c => c.ApplicationUser).
                SingleOrDefaultAsync(m => m.Id == id);

            if (car == null)
            {
                return NotFound();
            }
            return View(car);
         
        }
        //Edit GET
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var car = await _db.Cars.Include(c => c.ApplicationUser).
                SingleOrDefaultAsync(m => m.Id == id);

            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }
        //Delete GET
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var car = await _db.Cars.Include(c => c.ApplicationUser).
                SingleOrDefaultAsync(m => m.Id == id);

            if (car == null)
            {
                return NotFound();
            }
            return View(car);

        }

        //EDit POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Car car)
        {
            if(id != car.Id)
            {
                
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Update(car);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { userId = car.UserId});
            }
            return View(car);
        }

        //Delete POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _db.Cars.SingleOrDefaultAsync(c => c.Id == id);
            if(car == null)
            {
                return NotFound();
            }
            var services = _db.Services.Where(c=>c.CarId == car.Id);
            _db.RemoveRange(services);
            _db.Cars.Remove(car);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new {userId = car.UserId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
    }
}

Cars_ASPCore2/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Cars_ASPCore2.Models;
using Cars_ASPCore2.ViewModel;
using Cars_ASPCore2.Data;
using Microsoft.EntityFrameworkCore;
using Cars_ASPCore2.Utility;
using Microsoft.AspNetCore.Authorization;

namespace Cars_ASPCore2.Controllers
{
    public class ServicesController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ServicesController(ApplicationDbContext db)
        {
            _db = db;
        }
        [Authorize]
        public IActionResult Index(int carId)
        {
            var car = _db.Cars.FirstOrDefault(c => c.Id == carId);
            var model = new CarInServicesViewModel
            {
                CarId = car.Id,
                Make = car.Make,
                Model = car.Model,
                Style = car.Style,
                VIN = car.VIN,
                Year = car.Year,
                UserId = car.UserId,
                ServiceTypeObject = _db.ServiceTypes.ToList(),
                PastServiceObject = _db.Services.Where(s => s.CarId == carId).OrderByDescending(s => s.DateAdded)
            };

            return View(model);
        }
        [Authorize(Roles = StaticDetails.AdminEndUser)]
        //GET: Services/Create
        public IActionResult Create(int carId)
        {
            var car = _db.Cars.FirstOrDefault(c=>c.Id==carId);
            var model = new CarInServicesViewModel
            {
                CarId = car.Id,
                Make = car.Make,
                Model = car.Model,
                Style = car.Style,
                VIN = car.VIN,
                Year = car.Year,
                UserId = car.UserId,
                ServiceTypeObject = _db.ServiceTypes.ToList(),
                PastServiceObject = _db.Services.Where(s=>s.CarId == carId).OrderByDescending(s=>s.DateAdded).Take(5)
            };

            return View(model);
        }

        [Authorize(Roles = StaticDetails.AdminEndUser)]
        //POST: Services/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CarInServicesViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.NewServiceObj.CarId = model.CarId;
                model.NewServiceObj.DateAdded = DateTime.Now;
              
                _db.Add(model.NewServiceObj);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Create), new { carId = model.CarId });
            }
            var car = _db.Cars.FirstOrDefault(c => c.Id == model.CarId);
            var newModel = new CarInServicesViewModel
            {
                CarId = car.Id,
                Make = car.Make,
                Model = car.Model,
                Style = car.Style,
                VIN = car.VIN,
                UserId = car.UserId,

                ServiceTypeObject = _db.ServiceTypes.ToList(),
                PastServiceObject = _db.Services.Where(s => s.CarId == model.CarId).OrderByDescending(s => s.DateAdded).Take(5)
            };

            return View(newModel);
        }

        [Authorize(Roles = StaticDetails.AdminEndUser)]
        //Delete Get
        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var service = await _db.Services.Include(s => s.Car).Include(s => s.ServiceType).
                SingleOrDefaultAsync(m=>m.Id == id);
            if (service == null) return NotFound();
            //_db.Services.Remove(service);

            return View(service);
        }
        [Authorize(Roles = StaticDetails.AdminEndUser)]
        //Delete Post
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Service model)
        {
            var serviceId = model.Id;
            var carId = model.CarId;
            var service = await _db.Services.SingleOrDefaultAsync(s => s.Id == serviceId);
            if (service == null) return NotFound();
            _db.Services.Remove(service);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Create), new { carId = carId});
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
    }

  
}

Cars_ASPCore2/Views/Services/Create.cshtml
@model Cars_ASPCore2.ViewModel.CarInServicesViewModel
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>
<br/>
@Html.Partial("_CarDetailsInServicePartial")
<hr/>

<h4>Service</h4>
<div class="row form-border">
    <form asp-action="Create">
        <input asp-for="CarId" hidden />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @* miles and price *@
        <div class="col-sm-5">
            <div class="row">
                <div class="col-sm-3">
                    <label asp-for="NewServiceObj.Miles" class="control-label"></label>
                </div>
                <div class="col-sm-9" style="padding-bottom:5px;">
                    <input asp-for="NewServiceObj.Miles"  class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <label asp-for="NewServiceObj.Price" class="control-label"></label>
                </div>
                <div class="col-sm-9" style="padding-bottom:5px;">
                    <input asp-for="NewServiceObj.Price"  class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                </div>
                <div class="col-sm-9" style="padding-bottom:5px;">
                   <input type="submit" value="Add Service" class="btn btn-primary btn-sm form-control" /> 
                </div>
            </div>

        </div>

        @* details and servicetype *@
        <div class="col-sm-5 col-sm-offset-2">
            <div class="row">
                <div class="col-sm-3">
                    <label asp-for="NewServiceObj.Details" class="control-label"></label>
                </div>
                <div class="col-sm-9" style="padding-bottom:5px;">
                    <input asp-for="NewServiceObj.Details" class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <label asp-for="NewServiceObj.ServiceType" class="control-label"></label>
                </div>
                <div class="col-sm-9" style="padding-bottom:5px;">
                    <select asp-for="NewServiceObj.ServiceTypeId" asp-items="@(new SelectList(Model.ServiceTypeObject,"Id","Name"))" class="form-control"></select>
                </div>
            </div>
        </div>
    </form>
</div>
<br/>
<hr/>
<h4>Past Services</h4>
<div class="row form-border">
    @Html.Partial("_DisplayPastServices", Model)
    <div class="row">
        @if(Model.PastServiceObject.Count() == 0)
        {
            <div class="col-sm-12 text-primary" style="padding-bottom:20px;">
                No pas service record found.
            </div>
        }
        <div class="col-sm-3">
            <a asp-controller="Cars" asp-action="Index" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success">Back to list</a>
        </div>
        @if(Model.PastServiceObject.Count() > 4)
        {
            <div class="pull-right" style="padding-right:200px">
                <a asp-controller="Services" asp-action="Index" asp-route-carId="@Model.CarId"
                   class="text-primary">Load All..</a>
            </div>

        }
    </div>
</div>

Cars_ASPCore2/Views/Services/Delete.cshtml
@model Cars_ASPCore2.Models.Service
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<form asp-action="Delete">
    <div class="form-border">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="CarId" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Miles" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Miles" disabled class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="ServiceType.Name" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="ServiceType.Name" disabled class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Details" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Details" disabled class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Price" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Price" disabled class="form-control" />
                </div>
            </div>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Delete" class="btn-sm btn btn-danger" />
            <a asp-action="Create" asp-route-carId="@Model.CarId" class="btn btn-sm btn-success">Back to list</a>
        </div>
    </div>

</form>

Cars_ASPCore2/Views/Services/Index.cshtml
@model Cars_ASPCore2.ViewModel.CarInServicesViewModel
@{
    ViewData["Title"] = "Index";
}

<br />
@Html.Partial("_CarDetailsInServicePartial")
<hr />
<br />
<h2>Service Record</h2>
<div class="row form-border">
    @Html.Partial("_DisplayPastServices", Model)
    @if (Model.PastServiceObject.Count() > 0)
    {
        <input type="button" class="btn btn-sm btn-primary" value="Print" onclick="window.print();" />
    }

    <a asp-action="Index" asp-controller="Cars" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success ">
        Back to list
    </a>
</div>